DROP DATABASE IF EXISTS salon;

CREATE DATABASE salon

ALTER DATABASE salon OWNER TO freecodecamp;

\connect salon

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE customers (
  customer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(80) NOT NULL,
  phone varchar(20) NOT NULL UNIQUE,
  CONSTRAINT customers_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT customers_phone_not_blank CHECK (btrim(phone) <> '')
);

CREATE TABLE services (
  service_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL UNIQUE,
  CONSTRAINT services_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE appointments (
  appointment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL,
  service_id integer NOT NULL,
  "time" varchar(40) NOT NULL,
  CONSTRAINT appointments_time_not_blank CHECK (btrim("time") <> ''),
  CONSTRAINT appointments_customer_id_fkey
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT appointments_service_id_fkey
    FOREIGN KEY (service_id)
    REFERENCES services(service_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX appointments_customer_id_idx ON appointments(customer_id);
CREATE INDEX appointments_service_id_idx ON appointments(service_id);

ALTER TABLE customers OWNER TO freecodecamp;
ALTER TABLE services OWNER TO freecodecamp;
ALTER TABLE appointments OWNER TO freecodecamp;

INSERT INTO services(service_id, name) VALUES
  (1, 'cut'),
  (2, 'color'),
  (3, 'perm'),
  (4, 'style'),
  (5, 'trim');

SELECT setval(
  pg_get_serial_sequence('services', 'service_id'),
  (SELECT MAX(service_id) FROM services)
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO freecodecamp;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO freecodecamp;
